/*******************************************************************************
 * Copyright (C) 2026 Microchip Technology Inc. and its subsidiaries.
 *
 * Subject to your compliance with these terms, you may use Microchip software
 * and any derivatives exclusively with Microchip products. It is your
 * responsibility to comply with third party license terms applicable to your
 * use of third party software (including open source software) that may
 * accompany Microchip software.
 *
 * THIS SOFTWARE IS SUPPLIED BY MICROCHIP "AS IS". NO WARRANTIES, WHETHER
 * EXPRESS, IMPLIED OR STATUTORY, APPLY TO THIS SOFTWARE, INCLUDING ANY IMPLIED
 * WARRANTIES OF NON-INFRINGEMENT, MERCHANTABILITY, AND FITNESS FOR A
 * PARTICULAR PURPOSE.
 *
 * IN NO EVENT WILL MICROCHIP BE LIABLE FOR ANY INDIRECT, SPECIAL, PUNITIVE,
 * INCIDENTAL OR CONSEQUENTIAL LOSS, DAMAGE, COST OR EXPENSE OF ANY KIND
 * WHATSOEVER RELATED TO THE SOFTWARE, HOWEVER CAUSED, EVEN IF MICROCHIP HAS
 * BEEN ADVISED OF THE POSSIBILITY OR THE DAMAGES ARE FORESEEABLE. TO THE
 * FULLEST EXTENT ALLOWED BY LAW, MICROCHIP'S TOTAL LIABILITY ON ALL CLAIMS IN
 * ANY WAY RELATED TO THIS SOFTWARE WILL NOT EXCEED THE AMOUNT OF FEES, IF ANY,
 * THAT YOU HAVE PAID DIRECTLY TO MICROCHIP FOR THIS SOFTWARE.
 ******************************************************************************/

/*
 * user_filter.h - the filter "sigproc user" runs (src/core/sigproc.c).
 *
 * GENERATED by tools/filterdesign (dsPIC33 tab) by firmware.py --fixtures - do not edit by
 * hand: design the filter there and press "Install into firmware". The
 * description of the same filter for the dsPIC33 GUI is user_filter.json
 * next to this file (same id).
 *
 * Filter      : elliptic bandpass, order 6, 3 section(s)
 * Sample rate : 8000 Hz
 * Passband    : 800, 1200 Hz, max. 1 dB attenuation (achieved 0.52, 0.52 dB)
 * Stopband    : 400, 1800 Hz, min. 40 dB attenuation (achieved 52.12, 47.79 dB)
 * Arithmetic  : 16 bit fixed point (int16_t data/coefficients, int64_t accumulator)
 *
 * Structure   : 3 second order section(s), direct form I, 64 bit accumulator
 *               y = sat((b0*x + b1*x1 + b2*x2 - a1*y1 - a2*y2 + 2^(F-1)) >> F)
 * Coefficients: Q1.14 in int16_t (F = USER_FILTER_FRAC_BITS = 14, range +/-2)
 * Samples     : int16_t, any scaling (e.g. Q15); input and output use the same scaling
 * Note        : relies on an arithmetic right shift of negative int64_t values
 *               (true for GCC, Clang, XC16, XC32, IAR, Keil)
 */

/*
 * How sigproc.c drives it: the 12-bit ADC result x is centred, x - 2048,
 * and put into the top 12 bits of an int16_t (Q15: full scale = 1.0);
 * the result is shifted back with rounding, + 2048, clamped to 0..4095.
 * The filter's peak gain is 0 dB. On a gap in the stream the state is cleared.
 */
#ifndef USER_FILTER_H
#define USER_FILTER_H

#include <stddef.h>
#include <stdint.h>
#include <string.h>

#define USER_FILTER_ID          0x973E75F2u   /* CRC-32 of the code below */
#define USER_FILTER_DESC        "elliptic bandpass 800-1200 Hz, order 6, fixed16"
#define USER_FILTER_FS_HZ       8000u   /* designed for this sample rate */
#define USER_FILTER_FIXED_BITS  16   /* 0: floating point; else the word width of the samples */
typedef int16_t user_filter_sample_t;

#define USER_FILTER_NUM_SECTIONS 3
#define USER_FILTER_FRAC_BITS 14
#define USER_FILTER_SAMPLE_RATE 8000

typedef struct {
    int16_t x[USER_FILTER_NUM_SECTIONS][2];  /* x[n-1], x[n-2] */
    int16_t y[USER_FILTER_NUM_SECTIONS][2];  /* y[n-1], y[n-2] */
} user_filter_state_t;

#define USER_FILTER_MAX (32767)
#define USER_FILTER_MIN -32768
#define USER_FILTER_ROUND (((int64_t)1 << USER_FILTER_FRAC_BITS) >> 1)

/* per section: b0, b1, b2, a1, a2  (a0 = 1), Q14 */
static const int16_t user_filter_coeffs[USER_FILTER_NUM_SECTIONS][5] = {
    {   1502,       0,   -1502,  -21309,   13380}  /* 0.0916689973, 0, -0.0916689973, -1.300587, 0.816662849 */,
    {   4938,   -9275,    4938,  -25591,   15172}  /* 0.301365007, -0.566125575, 0.301365007, -1.5619746, 0.926017021 */,
    {   4639,    -617,    4639,  -18169,   14726}  /* 0.283157576, -0.0376875594, 0.283157576, -1.10894598, 0.898803969 */
};

static inline void user_filter_init(user_filter_state_t *st)
{
    memset(st, 0, sizeof *st);
}

static inline int16_t user_filter_process(user_filter_state_t *st, int16_t x)
{
    int k;

    for (k = 0; k < USER_FILTER_NUM_SECTIONS; k++) {
        const int16_t *c = user_filter_coeffs[k];
        int16_t *xs = st->x[k];
        int16_t *ys = st->y[k];
        int64_t acc = (int64_t)c[0] * x
                    + (int64_t)c[1] * xs[0]
                    + (int64_t)c[2] * xs[1]
                    - (int64_t)c[3] * ys[0]
                    - (int64_t)c[4] * ys[1];

        acc = (acc + USER_FILTER_ROUND) >> USER_FILTER_FRAC_BITS;
        if (acc > USER_FILTER_MAX) {
            acc = USER_FILTER_MAX;
        } else if (acc < USER_FILTER_MIN) {
            acc = USER_FILTER_MIN;
        }
        xs[1] = xs[0];
        xs[0] = x;
        ys[1] = ys[0];
        ys[0] = (int16_t)acc;
        x = (int16_t)acc;
    }
    return x;
}

static inline void user_filter_process_block(user_filter_state_t *st, const int16_t *in, int16_t *out, size_t n)
{
    size_t i;

    for (i = 0; i < n; i++) {
        out[i] = user_filter_process(st, in[i]);
    }
}

#endif /* USER_FILTER_H */
