/*******************************************************************************
 * Copyright (C) 2026 Microchip Technology Inc. and its subsidiaries.
 *
 * Subject to your compliance with these terms, you may use Microchip software
 * and any derivatives exclusively with Microchip products. It is your
 * responsibility to comply with third party license terms applicable to your
 * use of third party software (including open source software) that may
 * accompany Microchip software.
 *
 * THIS SOFTWARE IS SUPPLIED BY MICROCHIP "AS IS". NO WARRANTIES, WHETHER
 * EXPRESS, IMPLIED OR STATUTORY, APPLY TO THIS SOFTWARE, INCLUDING ANY IMPLIED
 * WARRANTIES OF NON-INFRINGEMENT, MERCHANTABILITY, AND FITNESS FOR A
 * PARTICULAR PURPOSE.
 *
 * IN NO EVENT WILL MICROCHIP BE LIABLE FOR ANY INDIRECT, SPECIAL, PUNITIVE,
 * INCIDENTAL OR CONSEQUENTIAL LOSS, DAMAGE, COST OR EXPENSE OF ANY KIND
 * WHATSOEVER RELATED TO THE SOFTWARE, HOWEVER CAUSED, EVEN IF MICROCHIP HAS
 * BEEN ADVISED OF THE POSSIBILITY OR THE DAMAGES ARE FORESEEABLE. TO THE
 * FULLEST EXTENT ALLOWED BY LAW, MICROCHIP'S TOTAL LIABILITY ON ALL CLAIMS IN
 * ANY WAY RELATED TO THIS SOFTWARE WILL NOT EXCEED THE AMOUNT OF FEES, IF ANY,
 * THAT YOU HAVE PAID DIRECTLY TO MICROCHIP FOR THIS SOFTWARE.
 ******************************************************************************/

/*
 * user_filter.h - the filter "sigproc user" runs (src/core/sigproc.c).
 *
 * GENERATED by tools/filterdesign (dsPIC33 tab) by firmware.py --fixtures - do not edit by
 * hand: design the filter there and press "Install into firmware". The
 * description of the same filter for the dsPIC33 GUI is user_filter.json
 * next to this file (same id).
 *
 * Filter      : elliptic bandpass, order 6, 3 section(s)
 * Sample rate : 8000 Hz
 * Passband    : 800, 1200 Hz, max. 1 dB attenuation (achieved 0.52, 0.52 dB)
 * Stopband    : 400, 1800 Hz, min. 40 dB attenuation (achieved 52.12, 47.79 dB)
 * Arithmetic  : 64 bit floating point (long double, XC-DSC's double is 32 bit)
 *
 * Structure   : 3 second order section(s), transposed direct form II
 *               y = b0*x + s0;  s0 = b1*x - a1*y + s1;  s1 = b2*x - a2*y
 */

/*
 * How sigproc.c drives it: the 12-bit ADC result x is centred, x - 2048,
 * as a floating-point number; the result + 2048 is rounded and clamped to 0..4095.
 * The filter's peak gain is 0 dB. On a gap in the stream the state is cleared.
 */
#ifndef USER_FILTER_H
#define USER_FILTER_H

#include <stddef.h>
#include <stdint.h>
#include <string.h>

#define USER_FILTER_ID          0x16BF3E1Eu   /* CRC-32 of the code below */
#define USER_FILTER_DESC        "elliptic bandpass 800-1200 Hz, order 6, double"
#define USER_FILTER_FS_HZ       8000u   /* designed for this sample rate */
#define USER_FILTER_FIXED_BITS  0   /* 0: floating point; else the word width of the samples */
typedef long double user_filter_sample_t;

#define USER_FILTER_NUM_SECTIONS 3
#define USER_FILTER_SAMPLE_RATE 8000

typedef struct {
    long double s[USER_FILTER_NUM_SECTIONS][2];
} user_filter_state_t;

/* per section: b0, b1, b2, a1, a2  (a0 = 1) */
static const long double user_filter_coeffs[USER_FILTER_NUM_SECTIONS][5] = {
    {0.091668997320881851L, 0.0L, -0.091668997320881851L, -1.3005870038172724L, 0.81666284891841512L},
    {0.30136500696184698L, -0.56612557482854675L, 0.30136500696184698L, -1.5619746047108922L, 0.92601702059266822L},
    {0.28315757617600618L, -0.037687559372713203L, 0.28315757617600618L, -1.1089459841661902L, 0.89880396948513364L}
};

static inline void user_filter_init(user_filter_state_t *st)
{
    memset(st, 0, sizeof *st);
}

static inline long double user_filter_process(user_filter_state_t *st, long double x)
{
    int k;

    for (k = 0; k < USER_FILTER_NUM_SECTIONS; k++) {
        const long double *c = user_filter_coeffs[k];
        long double *s = st->s[k];
        long double y = c[0] * x + s[0];

        s[0] = c[1] * x - c[3] * y + s[1];
        s[1] = c[2] * x - c[4] * y;
        x = y;
    }
    return x;
}

static inline void user_filter_process_block(user_filter_state_t *st, const long double *in, long double *out, size_t n)
{
    size_t i;

    for (i = 0; i < n; i++) {
        out[i] = user_filter_process(st, in[i]);
    }
}

#endif /* USER_FILTER_H */
